/**
 * Go-To-Market Plan Types
 * Defines the structure of plans generated by Gemini
 */

export type PlanStatus = 'draft' | 'ready' | 'executing' | 'completed' | 'failed';

export type ChannelType = 'X' | 'LinkedIn' | 'Instagram' | 'TikTok' | 'Email' | 'Blog';

/**
 * A single step in a channel's execution plan
 */
export interface PlanStep {
  id?: string;
  order: number;
  action: string;           // e.g., "post", "reply", "repost"
  content?: string;         // Text content
  mediaUrl?: string;        // Image/video URL
  scheduledAt?: string;     // ISO timestamp for scheduled execution
  status?: PlanStatus;
}

/**
 * Plan for a single channel
 */
export interface ChannelPlan {
  channel: ChannelType;
  sequence?: string;        // Campaign/sequence name
  target?: string;          // Target audience
  content?: string;         // Main content
  description?: string;     // Description or additional info (can include media URL)
  steps: PlanStep[];
  status?: PlanStatus;
}

/**
 * Complete Go-To-Market plan
 */
export interface GoToMarketPlan {
  id?: string;
  name?: string;
  description?: string;
  channels: ChannelPlan[];
  createdAt?: string;
  status?: PlanStatus;
}

/**
 * Execution result for a single channel
 */
export interface ChannelExecutionResult {
  channel: ChannelType;
  success: boolean;
  error?: string;
  skipped?: boolean;
  tweetId?: string;
  tweetUrl?: string;
  trackedPostId?: string;
  tweetsPlanned?: number;
  tweetsPosted?: number;
}

/**
 * Full execution result
 */
export interface ExecutionResult {
  success: boolean;
  message: string;
  results: ChannelExecutionResult[];
}

